-- AlterTable
ALTER TABLE "User" ADD COLUMN     "bicepsCm" DOUBLE PRECISION,
ADD COLUMN     "hipCm" DOUBLE PRECISION,
ADD COLUMN     "neckCm" DOUBLE PRECISION,
ADD COLUMN     "thighCm" DOUBLE PRECISION,
ADD COLUMN     "waistCm" DOUBLE PRECISION;
