-- Dữ liệu SQL để chèn 16 bài tập vào CSDL

INSERT INTO Workouts (Id, Name, Description, VideoUrl, ThumbnailUrl, MuscleGroups, Difficulty, Duration, Calories, Sets, Reps, Rest, Weight)
VALUES
('YOGA_BEGINNER_01', 'Morning Yoga Flow (20 Min)', 'Một bài tập yoga buổi sáng nhẹ nhàng (20 phút) để khởi động ngày mới, tập trung vào hơi thở và sự linh hoạt.', 'https://www.youtube.com/watch?v=4TLHLNX65-4', 'https://i.ytimg.com/vi/e-3S1M0YyvE/maxresdefault.jpg', '["Full Body", "Flexibility", "Mindfulness"]', 'Beginner', 20, 80, 1, '20 phút', 'N/A', 'Bodyweight'),
('PLANK_BEGINNER_01', 'Planks For Beginners', 'Hướng dẫn bài tập plank cơ bản cho người mới bắt đầu để xây dựng sức mạnh cốt lõi (core).', 'https://www.youtube.com/watch?v=ASdvN_XEl_c', 'https://i.ytimg.com/vi/bNcB0sSC7i0/maxresdefault.jpg', '["Core", "Abs"]', 'Beginner', 15, 150, 3, '30 giây', '30 giây', 'Bodyweight'),
('BEGINNER_ABS_01', '10 Min Beginner Abs', 'Bài tập bụng 10 phút cho người mới bắt đầu, không cần dụng cụ, tập ngay trên sàn.', 'https://www.youtube.com/watch?v=s27_b914-pg', 'https://i.ytimg.com/vi/s27_b914-pg/maxresdefault.jpg', '["Core", "Abs"]', 'Beginner', 10, 100, 1, '45s tập / 15s nghỉ', '15 giây', 'Bodyweight'),
('FULL_BODY_STRETCH_01', 'Full Body Stretch (15 Min)', 'Bài tập giãn cơ toàn thân 15 phút, tuyệt vời cho phục hồi sau tập hoặc giảm căng thẳng.', 'https://www.youtube.com/watch?v=Eogrw-I5-A8', 'https://i.ytimg.com/vi/Eogrw-I5-A8/maxresdefault.jpg', '["Full Body", "Flexibility"]', 'Beginner', 15, 50, 1, '15 phút', 'N/A', 'Bodyweight'),
('HIIT_FAT_LOSS_20', '20 Min HIIT Fat Loss - No Repeat Workout', 'Bài tập HIIT 20 phút toàn thân cường độ cao để đốt mỡ. Không lặp lại bài tập, không cần dụng cụ.', 'https://www.youtube.com/watch?v=zJKtwow2oBc', 'https://i.ytimg.com/vi/CBd8-34gq4A/maxresdefault.jpg', '["Full Body", "Cardio"]', 'Intermediate', 20, 350, 1, '45s tập / 15s nghỉ', '15 giây', 'Bodyweight'),
('FULL_BODY_STRENGTH_01', 'Full Body Strength - Week 1', 'Ngày 1 của chuỗi 28 ngày tập sức mạnh toàn thân với tạ dumbbell. Bao gồm các bài tập kết hợp.', 'https://www.youtube.com/watch?v=_jGebGZnYrU', 'https://i.ytimg.com/vi/pD3-yE-E0eE/maxresdefault.jpg', '["Full Body", "Strength"]', 'Intermediate', 45, 320, 4, 'Xem video', 'Xem video', 'Dumbbells'),
('HIIT_FAT_BURN_01', 'HIIT Fat Burn (HIIT x Cardio)', 'Bài tập HIIT x Cardio kết hợp để đốt mỡ toàn thân hiệu quả.', 'https://www.youtube.com/watch?v=YfIVllyojnQ', 'https://i.ytimg.com/vi/ypl8-v0-I-k/maxresdefault.jpg', '["Full Body", "Cardio"]', 'Intermediate', 25, 400, 1, '45s tập / 15s nghỉ', '15 giây', 'Bodyweight'),
('DUMBBELL_HIIT_01', '30 Min Dumbbell HIIT', 'Bài tập HIIT 30 phút sử dụng tạ dumbbell để tăng cường sức mạnh và đốt calo cùng lúc.', 'https://www.youtube.com/watch?v=1oD_bVf_UqY', 'https://i.ytimg.com/vi/1oD_bVf_UqY/maxresdefault.jpg', '["Full Body", "Cardio", "Strength"]', 'Intermediate', 30, 380, 3, '40s tập / 20s nghỉ', '20 giây', 'Dumbbells'),
('CORE_CRUSHER_01', 'Core & Abs Crusher (15 Min)', 'Tập trung ''nghiền nát'' cơ bụng và cơ lõi của bạn trong 15 phút.', 'https://www.youtube.com/watch?v=MiGCfVrA388', 'https://i.ytimg.com/vi/bNcB0sSC7i0/maxresdefault.jpg', '["Core", "Abs"]', 'Intermediate', 15, 150, 1, '45s tập / 15s nghỉ', '15 giây', 'Bodyweight'),
('UPPER_BODY_POWER_01', 'Upper Body Power', 'Tập trung vào sức mạnh phần thân trên (Đẩy, Kéo) và vai. Sử dụng trọng lượng cơ thể.', 'https://www.youtube.com/watch?v=c6w8ZyEioZM', 'https://i.ytimg.com/vi/fKYrLv3Qj2E/maxresdefault.jpg', '["Upper Body", "Chest", "Back", "Shoulders"]', 'Advanced', 25, 280, 4, '30s tập / 15s nghỉ', '15 giây', 'Bodyweight'),
('LEG_DAY_MASS_01', 'Dumbbell Legs Workout for Muscle', 'Bài tập 35 phút tập trung vào xây dựng cơ bắp cho phần thân dưới, bao gồm đùi và mông.', 'https://www.youtube.com/watch?v=ueNGcoH3o7M', 'https://i.ytimg.com/vi/ueNGcoH3o7M/maxresdefault.jpg', '["Legs", "Glutes", "Quads", "Hamstrings"]', 'Advanced', 35, 420, 3, '8-12 reps', '60-90 giây', 'Dumbbells'),
('CHEST_BACK_SUPERSET_01', 'Chest & Back Superset Workout', 'Tối đa hóa hiệu quả tập luyện với các superset (cặp bài tập) cho ngực và lưng.', 'https://www.youtube.com/watch?v=GGVqVAm9I2g', 'https://i.ytimg.com/vi/GGVqVAm9I2g/maxresdefault.jpg', '["Chest", "Back", "Upper Body"]', 'Advanced', 40, 450, 3, '10-12 reps', '90 giây (giữa superset)', 'Dumbbells/Cables'),
('SHOULDER_ARM_01', 'Shoulder & Arm Builder (30 Min)', 'Tập trung xây dựng cơ bắp cho vai, bắp tay trước và bắp tay sau.', 'https://www.youtube.com/watch?v=pYcpY20QaE8', 'https://i.ytimg.com/vi/pYcpY20QaE8/maxresdefault.jpg', '["Shoulders", "Arms", "Upper Body"]', 'Intermediate', 30, 290, 4, '10-15 reps', '60 giây', 'Dumbbells'),
('PLYOMETRIC_HIIT_01', 'Explosive Plyometric HIIT', 'Bài tập 25 phút tập trung vào sức mạnh bùng nổ (plyometric) để cải thiện tốc độ và đốt mỡ.', 'https://www.youtube.com/watch?v=s_dHT-EogIU', 'https://i.ytimg.com/vi/s_dHT-EogIU/maxresdefault.jpg', '["Full Body", "Cardio", "Legs"]', 'Advanced', 25, 430, 1, '30s tập / 15s nghỉ', '15 giây', 'Bodyweight'),
('ADVANCED_CORE_01', 'Advanced Core & Abs (20 Min)', 'Thử thách cơ lõi của bạn với bài tập bụng nâng cao 20 phút không nghỉ.', 'https://www.youtube.com/watch?v=4dGYBYM-n0M', 'https://i.ytimg.com/vi/4dGYBYM-n0M/maxresdefault.jpg', '["Core", "Abs"]', 'Advanced', 20, 250, 1, '50s tập / 10s nghỉ', '10 giây', 'Bodyweight'),
('FULL_BODY_DUMBBELL_01', 'Advanced Full Body Dumbbell', 'Một bài tập toàn thân nâng cao kéo dài 45 phút, chỉ sử dụng tạ dumbbell.', 'https://www.youtube.com/watch?v=Jb-t-_S1SjM', 'https://i.ytimg.com/vi/Jb-t-_S1SjM/maxresdefault.jpg', '["Full Body", "Strength"]', 'Advanced', 45, 500, 4, '10 reps', '60 giây', 'Dumbbells');